name: Deploy

run-name: Deploy to ${{ inputs.environment }}

env:
  FOO_PROD: foo-prod
  FOO_STAGE: foo-stage

on:
  workflow_call:
    inputs:
      application-name:
        required: true
        type: string
      primary-env-name:
        required: true
        type: string
      worker-env-name:
        required: true
        type: string
      environment:
        type: string
        description: environment to deploy to
        required: true
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        required: true
        default: 'warning'
        type: choice
        options:
          - staging
          - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - run: wget http://cdn.sencha.com/cmd/4.0.4.84/SenchaCmd-4.0.4.84-linux-x64.run.zip
      - run: unzip -o SenchaCmd-4.0.4.84-linux-x64.run.zip
      - run: chmod +x SenchaCmd-4.0.4.84-linux-x64.run
      - run: ./SenchaCmd-4.0.4.84-linux-x64.run --mode unattended --dir /opt/Sencha/Cmd/4.0.4.84
      - run: ls /opt/Sencha/Cmd/4.0.4.84
      - env:
          FOO: ${{ inputs.environment == 'production' && env.FOO_PROD || env.FOO_STAGE }}
        run: echo "hey-$FOO"
      - env:
          CNAME: "foo,bar,baz"
        run: |
          IFS=',' read -a array <<< "${{ env.CNAME }}"
          for name in "${array[@]}"; do
            echo "$name"
          done
          echo "${array[0]}"