name: Deploy

run-name: Deploy to ${{ inputs.environment }}

env:
  FOO_PROD: foo-prod
  FOO_STAGE: foo-stage

on:
  # push:
  workflow_call:
    inputs:
      application-name:
        required: true
        type: string
      primary-env-name:
        required: true
        type: string
      worker-env-name:
        required: true
        type: string
      environment:
        type: string
        description: environment to deploy to
        required: true
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        required: true
        default: 'warning'
        type: choice
        options:
          - staging
          - production
      cond-1:
        required: false
        type: boolean
      cond-2:
        required: false
        type: boolean
      cond-3:
        required: false
        type: boolean

jobs:
  cond-1:
    if: inputs.cond-1
    runs-on: ubuntu-latest
    steps:
      - run: echo "cond 1"
  cond-2:
    needs: [cond-1]
    if: always() && !contains(needs.*.result, 'failure') && inputs.cond-2
    runs-on: ubuntu-latest
    steps:
      - run: echo "cond 2"
  cond-3:
    needs: [cond-1, cond-2]
    if: always() && !contains(needs.*.result, 'failure') && inputs.cond-3
    runs-on: ubuntu-latest
    steps:
      - run: echo "cond 3"
  deploy:
    runs-on: ubuntu-latest
    # environment: ${{ inputs.environment }}
    steps:
      - run: wget http://cdn.sencha.com/cmd/4.0.4.84/SenchaCmd-4.0.4.84-linux-x64.run.zip
      - run: unzip -o SenchaCmd-4.0.4.84-linux-x64.run.zip
      - run: chmod +x SenchaCmd-4.0.4.84-linux-x64.run
      - run: ./SenchaCmd-4.0.4.84-linux-x64.run --mode unattended --prefix /opt/Sencha/Cmd/4.0.4.84
      - run: ls -lart /opt/Sencha/Cmd/4.0.4.84/Sencha/Cmd/4.0.4.84
      - env:
          SENCHA_CMD_3_0_0: /opt/Sencha/Cmd
        run: echo $SENCHA_CMD_3_0_0
      - env:
          FOO: ${{ inputs.environment == 'production' && env.FOO_PROD || env.FOO_STAGE }}
        run: echo "hey-$FOO"
      - env:
          CNAME: "foo,bar,baz"
        run: |
          IFS=',' read -a array <<< "${{ env.CNAME }}"
          for name in "${array[@]}"; do
            echo "$name"
          done
          echo "${array[0]}"